#### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 만들어진                        
  의사결정 트리를 기반으로 다수결로 결과를 유도하는 모델

In [33]:
# Feature와 Target 분리
from sklearn.datasets import load_iris
iris = load_iris() # Bunch Class
iris_data = iris['data'] 
iris_target = iris['target']
iris_data.shape
iris_target.shape

(150,)

In [7]:
from sklearn.model_selection import train_test_split

In [15]:
train_data, test_data, train_target, test_target = \
    train_test_split(
        iris_data,
        iris_target,
        random_state=42,
        stratify=iris_target
    )

#### RandomForest로 분류

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# 모델 만들기
clf = RandomForestClassifier()

In [ ]:
# 학습 시키기
clf.fit(train_data, train_target)

RandomForestClassifier()

In [ ]:
# 평가하기
clf.score(test_data, test_target)

0.9210526315789473

----
#### 독버섯과 관련된 데이터를 사용한 머신러닝
- 8124종류의 버섯의 특징과 독의 유무로 구성되어 있는 데이터셋
- 버섯의 특징을 기반으로 독의 유무를 판단

In [25]:
# 데이터 획득하기
import urllib.request as req

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print('OK')

OK

#### 랜덤포레스트를 이용한 버섯 종류

In [27]:
import pandas as pd
mr = pd.read_csv("../Data/mushroom.csv", header=None)
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [28]:
mr.shape

(8124, 23)

- 한 줄이 버섯 한 종류
- 첫번째 열 : p(독버섯), e(식용)
- 두번째 열 : 버섯의 머리 모양 -> b(벨형태), c(원뿔), x(볼록), f(평평),k(혹),s(오목)
- 네번째 열 : 버섯의 머리 색깔 -> n(갈색), b(황갈색), c(연한갈색)

### Feature Data가 알파벳 1자리 문자 -> 숫자로 변환

-----
#### 연습

In [34]:
# 알파벳 -> ASCII
ord('x')

120

In [35]:
# ASCII -> 알파벳
chr(120)

'x'

In [ ]:
# mr의 1번 컬럼을 숫자로 변경
for i in mr.loc[:, 1]:
    print(i, ord(i))

------

In [41]:
target = []
data = []

for row_index, row in mr.iterrows():
    # print(row_index, ":", row)
    # print(row.loc[0])
    # print(row.loc[1])
    # print('-----------------')
    target.append(row.loc[0])
    row_data = []
    for v in row.loc[1:]:
        row_data.append(ord(v))
    data.append(row_data)

In [43]:
print(data[:2])
print(target[:2])

[[120, 115, 110, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 117], [120, 115, 121, 116, 97, 102, 99, 98, 107, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 103]]
['p', 'e']

#### DataFrame 만들기

In [91]:
# Target을 기준으로 DataFrame 만들기
targetTemp = pd.DataFrame(target)
targetTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [92]:
# data를 dataFrame으로 만들고 column 이름을 겹치지 않게 하기.
dataTemp = pd.DataFrame(data)
dataTemp.rename(columns=lambda x : x+1, inplace=True)
dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [93]:
# 2개의 dataframe 합치기
mr2 = pd.concat([targetTemp, dataTemp], axis='columns')
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [ ]:
mr2.info()

#### RandomForest로 분류하기

In [94]:
# Train과 Test 분리
train_data, test_data, train_target, test_target = \
    train_test_split(
        mr2.loc[:, 1:],
        mr2.loc[:, 0],
        random_state=42,
        stratify=mr2.loc[:, 0]
    )

In [95]:
# 모델 만들기
clf = RandomForestClassifier()
clf.fit(train_data, train_target)
print("Training:", clf.score(train_data, train_target))
print("Test:", clf.score(test_data, test_target))

Training: 1.0
Test: 1.0

---
#### one-hot Encoding
- 숫자 데이터가 숫자로써 의미가 있으면 상관 없지만, 위의 데이터는 분류를
  위한 데이터이므로 숫자 크기의 의미가 없다.
- 이때 사용하는것이 one-hot Encoding 이다.

----
#### 연습

In [96]:
# 1번열
dataTemp[1].unique()

array([120,  98, 115, 102, 107,  99])

In [97]:
pd.get_dummies(
    data=dataTemp,
    columns=[1],
    prefix='1'
)

,2,3,4,5,6,7,8,9,10,11,...,19,20,21,22,1_98,1_99,1_102,1_107,1_115,1_120
0,115,110,116,112,102,99,110,107,101,101,...,112,107,115,117,False,False,False,False,False,True
1,115,121,116,97,102,99,98,107,101,99,...,112,110,110,103,False,False,False,False,False,True
2,115,119,116,108,102,99,98,110,101,99,...,112,110,110,109,True,False,False,False,False,False
3,121,119,116,112,102,99,110,110,101,101,...,112,107,115,117,False,False,False,False,False,True
4,115,103,102,110,102,119,98,107,116,101,...,101,110,97,103,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,115,110,102,110,97,99,98,121,101,63,...,112,98,99,108,False,False,False,True,False,False
8120,115,110,102,110,97,99,98,121,101,63,...,112,98,118,108,False,False,False,False,False,True
8121,115,110,102,110,97,99,98,110,101,63,...,112,98,99,108,False,False,True,False,False,False
8122,121,110,102,121,102,99,110,98,116,63,...,101,119,118,108,False,False,False,True,False,False
8123,115,110,102,110,97,99,98,121,101,63,...,112,111,99,108,False,False,False,False,False,True

----

In [98]:
# 적용하기
for i in range(1, 22+1):
    dataTemp = pd.get_dummies(
        data = dataTemp,
        columns=[i],
        prefix=str(i)
    )

In [99]:
# dataFrame 만들기
mr3 = pd.concat(
    [targetTemp, dataTemp],
    axis='columns'
)
mr3.head()

,0,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,p,False,False,False,False,False,True,False,False,True,...,True,False,False,False,False,False,False,False,True,False
1,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,e,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
3,p,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
4,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False

In [101]:
# Train과 Test 분리
train_data, test_data, train_target, test_target = \
    train_test_split(
        mr3.iloc[:, 1:],
        mr3.iloc[:, 0],
        random_state=42,
        stratify=mr3.iloc[:, 0]
    )

In [102]:
# 모델 만들기
clf = RandomForestClassifier()
clf.fit(train_data, train_target)
print("Training:", clf.score(train_data, train_target))
print("Test:", clf.score(test_data, test_target))

Training: 1.0
Test: 1.0